branches:
  - main

plugins:
  - 
    - "@semantic-release/commit-analyzer"
    - preset: "angular"
  - 
    - "@google/semantic-release-replace-plugin"
    - replacements:
      - files:
        - "pyproject.toml"
        from: '(?<=\[tool\.poetry\]\n(?:.*\n)*)version = ".*"'
        to: "version = '${nextRelease.version}'"
        results:
          - file: "pyproject.toml"
            hasChanged: true
            numMatches: 1
            numReplacements: 1
        countMatches: true
  - 
    - "@codedependant/semantic-release-docker"
    -  dockerRegistry: "ghcr.io"
       dockerImage: "squent/stressed-pod"
  - "@semantic-release/release-notes-generator"  
  - 
    - "@semantic-release/git"
    - assets:
      - "pyproject.toml"
  - "@semantic-release/github"
  - "@semantic-release/changelog"
 
