name: Test and Lint on PR

on:
  pull_request:
    branches:
      - main

jobs:
  lint_and_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install poetry
          poetry install

      - name: Run linter
        run: poetry run flake8

      - name: Run tests
        run: |
          poetry run pytest